#!/usr/bin/perl
#funguje to staci pridat kopirovani
open(IN,"<knownlist") || die("Can't open knownlist");
while (<IN>) {
	chop;
	($file,$name)=split(/:/);
        $name=~s/ *$//;
	$name=~tr/A-Z/a-z/;
	$name=~s/[^a-z]/ /g;
	$name=~s/ +/ /g;
#	print "#$name#$file#\n";
	$list{$name}=$file;
}
close(IN);

open(IN,"<findlist") || die("Can't open findlist");
while (<IN>) {
	chop;
	$file='';
        ($name,$file,$pad)=split(/\|/);
        $_=$name;
        s/ *$//;
	tr/A-Z/a-z/;
	s/[^a-z]/ /g;
	s/ +/ /g;
	if (!$file) {$file=$list{$_};};
	if ($file) {
                print "-----\n";
                open(SONG,"<$file") || die("no file $file");
                while (<SONG>) {print;}
                close(SONG);
	}
}



close(IN);
		
	

